import Head from 'next/head';
import Header from '../../organisms/Header/Header';
import styles from './Layout.module.scss';
import clsx from 'clsx';
import Footer from '@/components/organisms/Footer/Footer';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import BreadCrumbs from '@/components/molecules/BreadCrumbs/BreadCrumbs';

function Layout({ children }) {
	const router = useRouter();
	const [Path, setPath] = useState([]);
	const [IsShow, setIsShow] = useState(true);

	useEffect(() => {
		const arr = router.asPath.split('/');
		setPath(arr);
		//router경로가 바뀔때마다 순간적으로 IsShow값을 false로 바꿨다가
		setIsShow(false);
		//페이지전환 모션이 끝나는 0.5초 뒤에 다시 true로 변경
		setTimeout(() => setIsShow(true), 500);
	}, [router]);

	return (
		<>
			<Head>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={clsx(styles.layout)}>
				<Header />
				<section className={clsx(styles.content)}>
					{/* 해당 브래드크럼의 활성화 유무를 IsShow값으로 연동 */}
					<BreadCrumbs data={Path} isActive={IsShow} />
					{children}
				</section>
				<Footer />
			</main>
		</>
	);
}

export default Layout;
