import Head from 'next/head';
import Header from '../../organisms/Header/Header';
import styles from './Layout.module.scss';
import clsx from 'clsx';
import Footer from '@/components/organisms/Footer/Footer';
import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';
import BreadCrumbs from '@/components/molecules/BreadCrumbs/BreadCrumbs';

function Layout({ children }) {
	const router = useRouter();
	const [Path, setPath] = useState([]);
	const [IsShow, setIsShow] = useState(true);
	const [IsMain, setIsMain] = useState(true);

	useEffect(() => {
		const arr = router.asPath.split('/');
		setPath(arr);
		setIsShow(false);
		setIsMain(router.asPath === '/');
		setTimeout(() => setIsShow(true), 500);
	}, [router]);

	return (
		<>
			<Head>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={clsx(styles.layout)}>
				<Header />
				<section className={clsx(styles.content)}>
					<BreadCrumbs data={Path} isActive={IsShow && !IsMain} />
					{children}
				</section>
				<Footer />
			</main>
		</>
	);
}

export default Layout;
