import Head from 'next/head';
import styles from './Home.module.scss';
import clsx from 'clsx';
import axios from 'axios';
import Visual from '@/components/pic/Visual';

//https://www.themealdb.com
export default function Home({ meals }) {
	const newMeals = meals.slice(0, 6);
	console.log(newMeals);

	return (
		<>
			<Head>
				<title>Next Recipe</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={clsx(styles.main)}>
				<figure className='visual'>
					<article className='bg'>
						{newMeals.map((item) => (
							<Visual key={item.idMeal} imgSrc={item.strMealThumb} />
						))}
					</article>

					<article className='list'>
						{newMeals.map((item) => (
							<h2 key={item.idMeal}>{item.strMeal}</h2>
						))}
					</article>
				</figure>
			</main>
		</>
	);
}

export async function getStaticProps() {
	//props로 데이터 넘길때에는 data안쪽의 값까지 뽑아낸다음에 전달
	const { data } = await axios.get('/filter.php?c=Seafood');
	console.log('data fetching on Server', data);

	return {
		props: data,
		revalidate: 60 * 60 * 24,
	};
}
