import Head from 'next/head';
import styles from './Home.module.scss';
import clsx from 'clsx';
import axios from 'axios';
import Title from '@/components/atoms/text/Title';
import Text from '@/components/atoms/text/Text';

export default function Home({ meals }) {
	//idMeal
	//strMeal
	//strMealThumb
	console.log(meals);
	return (
		<>
			<Head>
				<title>Next Recipe</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={clsx(styles.main)}>
				{/* 해당 요소를 활성화 시키고 싶을때에는 props으로 boolean값 전달 */}
				<Text type={'breadcrumb'} tag={'span'} isOn={true}>
					Lorem ipsum dolor sit amet consectetur adipisicing elit.
					Tempora, amet!
				</Text>
			</main>
		</>
	);
}

export async function getStaticProps() {
	const { data } = await axios.get('/filter.php?c=Seafood');
	console.log('data fetching on Server', data);

	return {
		props: data,
		revalidate: 60 * 60 * 24,
	};
}
